# Generated by Django 5.1.7 on 2025-03-07 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_estado_alter_cliente_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
    ]
