# Generated by Django 5.1.7 on 2025-03-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_cliente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='abono',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Abono'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='debe, o pagado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numeros',
            field=models.JSONField(default=list, verbose_name='numeros jugados'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='telefono'),
        ),
    ]
