# Generated by Django 5.1.7 on 2025-03-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_abono_cliente_estado_alter_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['fecha_registro']},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=11, verbose_name='telefono'),
        ),
    ]
